-- =============================================
-- YESZZ TECH — Seed Sample Posts
-- Run AFTER categories are seeded (05-seed-categories.sql)
-- NOTE: Only inserts columns that exist. If you haven't added 'status' column, remove it.
-- =============================================

-- Insert sample posts using category IDs from the categories table
INSERT INTO public.posts (title, slug, summary, content, image_url, category_id, published, featured, trending, read_time, published_at, meta_description) VALUES

-- AI Posts
('The Rise of Multimodal AI Models', 'rise-of-multimodal-ai', 'How AI models that understand text, images, and audio are reshaping every industry.', '<h2>What Are Multimodal AI Models?</h2><p>Multimodal AI models process and generate multiple types of data—text, images, audio, and video—simultaneously. This marks a fundamental shift from single-purpose AI systems.</p><h2>Key Players</h2><p>Companies like OpenAI, Google, and Anthropic are leading the charge with models that can understand context across different media types.</p><h2>Real-World Impact</h2><p>From healthcare diagnostics to creative content generation, multimodal AI is unlocking capabilities that were impossible just two years ago.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'ai'), true, true, true, '6 min', now(), 'Explore how multimodal AI models are transforming industries'),

('AI Agents: The Next Frontier in Automation', 'ai-agents-automation', 'Autonomous AI agents are moving from demos to production systems.', '<h2>Beyond Chatbots</h2><p>AI agents go beyond simple Q&A—they can plan, execute multi-step tasks, use tools, and learn from feedback in real-time.</p><h2>Enterprise Adoption</h2><p>Companies are deploying AI agents for customer support, code review, data analysis, and workflow automation.</p>', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'ai'), true, false, true, '5 min', now(), 'How AI agents are revolutionizing business automation'),

-- Cybersecurity Posts
('Zero Trust Architecture: A Complete Guide', 'zero-trust-architecture-guide', 'Why "never trust, always verify" is now the gold standard for enterprise security.', '<h2>What Is Zero Trust?</h2><p>Zero Trust is a security framework that requires all users, whether inside or outside the network, to be authenticated and continuously validated.</p><h2>Implementation Steps</h2><p>1. Identify your protect surface<br>2. Map transaction flows<br>3. Build a Zero Trust architecture<br>4. Create Zero Trust policies<br>5. Monitor and maintain</p>', 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'cybersecurity'), true, true, false, '8 min', now(), 'Complete guide to implementing Zero Trust security'),

('The State of Ransomware in 2026', 'ransomware-2026', 'Ransomware attacks are evolving—here is what security teams need to know.', '<h2>Evolving Tactics</h2><p>Modern ransomware groups use double and triple extortion, targeting backups and threatening data leaks alongside encryption.</p><h2>Defense Strategies</h2><p>Immutable backups, network segmentation, and employee training remain the most effective defenses.</p>', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'cybersecurity'), true, false, false, '7 min', now(), 'Latest ransomware trends and defense strategies'),

-- Gadgets Posts
('Best Smartphones of 2026: Our Top Picks', 'best-smartphones-2026', 'We tested dozens of phones—these are the ones worth your money.', '<h2>Top Overall: Samsung Galaxy S26 Ultra</h2><p>The S26 Ultra combines the best camera system with exceptional battery life and the most polished AI features.</p><h2>Best Value: Pixel 10a</h2><p>Google flagship experience at mid-range pricing with 7 years of updates.</p>', 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'gadgets'), true, true, true, '10 min', now(), 'Top smartphone picks for 2026'),

('Smart Home Devices That Actually Matter', 'smart-home-devices-2026', 'Cut through the noise—these smart home gadgets genuinely improve daily life.', '<h2>Matter Protocol Changes Everything</h2><p>With Matter now widely adopted, interoperability issues are finally solved. Devices from different brands work together seamlessly.</p><h2>Our Recommendations</h2><p>Smart locks, energy monitors, and AI-powered thermostats provide the highest ROI for most households.</p>', 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'gadgets'), true, false, false, '6 min', now(), 'Essential smart home devices for 2026'),

-- Programming Posts
('Rust vs Go in 2026: Which Should You Learn?', 'rust-vs-go-2026', 'A practical comparison of two modern systems languages for different use cases.', '<h2>When to Choose Rust</h2><p>Rust excels when you need memory safety without garbage collection—systems programming, WebAssembly, and performance-critical applications.</p><h2>When to Choose Go</h2><p>Go shines for cloud services, CLI tools, and projects where developer velocity matters more than zero-cost abstractions.</p>', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'programming'), true, false, true, '8 min', now(), 'Rust vs Go comparison for modern developers'),

('Building Type-Safe APIs with tRPC and Zod', 'type-safe-apis-trpc-zod', 'End-to-end type safety from database to frontend without code generation.', '<h2>The Problem</h2><p>Traditional REST APIs require manual type synchronization between backend and frontend, leading to runtime errors.</p><h2>The tRPC Solution</h2><p>tRPC eliminates this gap entirely—your TypeScript types flow from server to client automatically.</p>', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'programming'), true, false, false, '7 min', now(), 'End-to-end type-safe APIs with tRPC'),

-- Startups Posts
('How to Raise a Seed Round in 2026', 'raise-seed-round-2026', 'The fundraising landscape has shifted—here is what founders need to know.', '<h2>The New Normal</h2><p>Seed rounds now range from $1M to $5M, with investors expecting more traction before writing checks.</p><h2>Key Metrics</h2><p>Revenue growth rate, retention, and unit economics matter more than TAM slides.</p>', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'startups'), true, true, false, '9 min', now(), 'Guide to raising seed funding in 2026'),

('10 Developer Tools Startups to Watch', 'devtools-startups-2026', 'These under-the-radar startups are building the next generation of developer tooling.', '<h2>The DevTools Renaissance</h2><p>Developer tools are experiencing a golden age with AI-augmented IDEs, automated testing platforms, and infrastructure-as-code tools.</p><h2>Our Picks</h2><p>From AI code review to automated database migrations, these startups are solving real developer pain points.</p>', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'startups'), true, false, true, '6 min', now(), 'Top developer tools startups to watch'),

-- Reviews Posts
('MacBook Pro M5 Review: Worth the Upgrade?', 'macbook-pro-m5-review', 'Apple M5 silicon delivers jaw-dropping performance—but is it enough to upgrade?', '<h2>Performance</h2><p>The M5 chip delivers 40% faster CPU and 50% faster GPU compared to M4, making it the fastest laptop we have ever tested.</p><h2>Battery Life</h2><p>22 hours of real-world usage. Enough said.</p><h2>Verdict</h2><p>If you are on M3 or older, this is a no-brainer upgrade. M4 users can safely wait.</p>', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'reviews'), true, false, true, '8 min', now(), 'In-depth review of the MacBook Pro with M5 chip'),

('VS Code vs Cursor: The AI Editor Showdown', 'vscode-vs-cursor-2026', 'Two editors, two approaches to AI-assisted coding—which one wins?', '<h2>VS Code + Copilot</h2><p>The familiar choice with deep extension ecosystem and GitHub Copilot integration.</p><h2>Cursor</h2><p>Built from the ground up for AI-first development with superior context understanding.</p><h2>Our Pick</h2><p>Cursor edges ahead for AI-heavy workflows, but VS Code extension ecosystem remains unmatched.</p>', 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80', (SELECT id FROM public.categories WHERE slug = 'reviews'), true, false, false, '7 min', now(), 'VS Code vs Cursor AI editor comparison')

ON CONFLICT (slug) DO NOTHING;
