-- =============================================
-- YESZZ TECH — Seed Tags
-- =============================================

INSERT INTO public.tags (name, slug) VALUES
  ('Machine Learning', 'machine-learning'),
  ('Deep Learning', 'deep-learning'),
  ('NLP', 'nlp'),
  ('Computer Vision', 'computer-vision'),
  ('LLMs', 'llms'),
  ('GPT', 'gpt'),
  ('React', 'react'),
  ('TypeScript', 'typescript'),
  ('JavaScript', 'javascript'),
  ('Python', 'python'),
  ('Rust', 'rust'),
  ('Go', 'go'),
  ('Next.js', 'nextjs'),
  ('Node.js', 'nodejs'),
  ('Docker', 'docker'),
  ('Kubernetes', 'kubernetes'),
  ('AWS', 'aws'),
  ('Firebase', 'firebase'),
  ('PostgreSQL', 'postgresql'),
  ('GraphQL', 'graphql'),
  ('REST API', 'rest-api'),
  ('Web3', 'web3'),
  ('Solidity', 'solidity'),
  ('Smart Contracts', 'smart-contracts'),
  ('Privacy', 'privacy'),
  ('Encryption', 'encryption'),
  ('Penetration Testing', 'penetration-testing'),
  ('Open Source', 'open-source'),
  ('Startup Funding', 'startup-funding'),
  ('Product Hunt', 'product-hunt'),
  ('UPI', 'upi'),
  ('Digital India', 'digital-india'),
  ('5G', '5g'),
  ('AR/VR', 'ar-vr'),
  ('Quantum Computing', 'quantum-computing'),
  ('Edge Computing', 'edge-computing'),
  ('Microservices', 'microservices'),
  ('CI/CD', 'ci-cd'),
  ('Terraform', 'terraform'),
  ('Linux', 'linux')
ON CONFLICT (name) DO NOTHING;
